### ISSUE TITLE
give player lasers

### ISSUE THREAD

**Issue by emeraldvision** [dummey/CS50-Cohort-Project-Redux#17]
Notes:
- [x] Create a `laser_beam' class
  - [x] gosu methods like `draw` and `update`
    - [x] update should enforce wrapping
    - [x] draw should draw image from `Lasers/LaserXXXXX.png`
  - [x] Laserbeam needs chipmunk properties `body` and `shape`
  - [x] `shape` should be sensor
  - [x] `shape` needs `collision_type`
  - [x]  `body` shouldn't allow dampening (override velocity_func ??)
  - [x] needs method `fire` takes starting position, angle, and velocity of player
    - [x] to accelerate, body.v = 2\* 'player max_velocity'
    - [x] after changing `velocity` on non moving shape `body.activate`must be called. (says chipmunk [docs](http://beoran.github.io/chipmunk/#Body))
  - [x] needs `reached_range` returns true when it's moved the range of the laser (is this hard with edge wrapping??)
- [x] player needs `fire` method takes a laser beam as argument
  - [x] calls `beam.fire` (basically double dispatching so that in the scene on the key press it's `player.fire(laser_beam.new)`)
- [x] game_scene needs list of `laser_beam`s
  - [x] call fire on key press add beam to list and `space`
  - [x] update check list for items that have `reached_range` remove them from list and `space`
  - [x] collision handler for laser_beam & ufo's (kill them all!! :smiling_imp:) and force range_reached to true
  - [x] Update Score!

**Comment by jbtule** [comment]
Notes:
- [ ] Create a `laser_beam' class
   - [ ] gosu properties like `draw` and `update`
      - [ ] update should enforce wrapping
   - [ ] Laserbeam needs chipmunk properties `body` and `shape`
   - [ ] `shape` should be sensor
   - [ ] `shape` needs `collision_type`
   - [ ]  `body` shouldn't allow dampening (override velocity_func ??)
   - [ ] needs method `fire` takes starting position and velocity of player
        - [ ] to accelerate, body.v = `velocity` + `player velocity`
        - [ ] after changing `velocity` on non moving shape `body.activate`must be called. (says chipmunk [docs](http://beoran.github.io/chipmunk/#Body))
   - [ ] needs `reached_range` returns true when it's moved the range of the laser (is this hard with edge wrapping??)
- [ ] player needs `fire` method takes a laser beam as argument
  - [ ] calls `beam.fire` (basically double dispatching so that in the scene on the key press it's `player.fire(laser_beam.new)`)
- [ ] game_scene needs list of `laser_beam`s
  - [ ] call fire on key press add beam to list and `space`
  - [ ] update check list for items that have `reached_range` remove them from list and `space`
  - [ ] collision handler for laser_beam & ufo's (kill them all!! :smiling_imp:) and force range_reached to true

**Comment by emeraldvision** [comment]
How about updating score when UFOs are hit?

**Comment by dummey** [comment]
Do its!

**Comment by jbtule** [comment]
@dummey added collisions to kill ufo's. But @emeraldvision still needs to make reach_ranged set on lasers in that case  045829a64f7cbe363a2b5ad1f6209f9c090dc2e6
